---
kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: arm64

steps:
  - name: build-cms
    image: docker:dind
    privileged: true
    environment:
      DOCKER_BUILDKIT: 1
      CR_PAT:
        from_secret: REGISTRY_PASSWORD
      CR_USER:
        from_secret: REGISTRY_USERNAME
    commands:
      - sleep 5
      - echo $CR_PAT | docker login ghcr.io -u $CR_USER --password-stdin
      - docker build -t ghcr.io/gngz/page/cms:latest -f ./docker/cms.Dockerfile .
      - docker push ghcr.io/gngz/page/cms:latest
    # settings:
    #   repo: ghcr.io/gngz/page/cms
    #   tags:
    #     - latest
    #   dockerfile: ./docker/cms.Dockerfile
    #   context: .
    #   registry: ghcr.io
    #   username:
    #     from_secret: REGISTRY_USERNAME
    #   password:
    #     from_secret: REGISTRY_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run
      - name: cache
        path: /pnpm/store
services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
volumes:
  - name: cache
    host:
      path: /pnpm/store

---
kind: pipeline
name: hello
type: exec

platform:
  os: linux
  arch: arm64

steps:
  - name: update docker image
    environment:
      CR_PAT:
        from_secret: REGISTRY_PASSWORD
      CR_USER:
        from_secret: REGISTRY_USERNAME
    commands:
      - echo $CR_PAT | docker login ghcr.io -u $CR_USER --password-stdin
      - docker pull ghcr.io/gngz/page/cms:latest
depends_on:
  - build
