---
kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: arm64

steps:
  - name: build-cms
    image: plugins/docker
    privileged: true
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
    - name: cache
      path: /pnpm/store
    settings:
      repo: ghcr.io/gngz/page/cms
      tags:
        - latest
      dockerfile: ./docker/cms.Dockerfile
      context: .
      registry: ghcr.io
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
volumes:
- name: cache
  host:
    path: /pnpm/store

---
kind: pipeline
name: hello
type: exec

platform:
  os: linux
  arch: arm64

steps:
  - name: update docker image
    environment:
      CR_PAT:
        from_secret: REGISTRY_PASSWORD
      CR_USER:
        from_secret: REGISTRY_USERNAME
    commands:
      - echo $CR_PAT | docker login ghcr.io -u $CR_USER --password-stdin
      - docker pull ghcr.io/gngz/page/cms:latest
depends_on:
  - build
