---
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build-cms
    image: plugins/docker
    settings:
      repo: page-cms
      tags:
        - latest
      dockerfile: ./docker/cms.Dockerfile
      context: .
